name = "notepad_gui"

plushie_rust_version = "0.7.1"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
plushie_gleam = "== 0.6.0"
#plushie_gleam = { path = "./plushie-gleam" }
file_system = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
